### ISSUE TITLE
RecyclerView条数不够一屏的空白问题

### ISSUE THREAD

**Issue by AndyGu** [HzwSunshine/NestedWebViewRecyclerViewGroup#2]
嵌套的RecyclerView的高度 是不是最小是一屏的高度？
当把测试的RecyclerView的数据减至只有一条时，下面会有大量空白区域，即使将RecyclerView的高度设为wrap_content也没有效果，应该是在NestedWebViewRecyclerViewGroup的onMeasure里处理这个吧？

**Comment by HzwSunshine** [comment]
@AndyGu 是的，RV的高度默认为父控件的高度，因为涉及到滑动事件的传递，触摸事件以及WebView和RV上下的切换，对于RV的高度自适应目前没有很好的办法解决，后面有时间会尝试去解决一下

**Comment by HzwSunshine** [comment]
1.2.1版本已解决！ yeah！done！

**Comment by AndyGu** [comment]
恩恩，现在还有个问题是：如果webview不满一屏，但是recyclerview有数据，那么webview因为设置了match_parent，会占满一屏，下面会留白一部分，向上滑动露出recyclerview，但是把webview设置成wrap_content的话又会闪屏，不知道有没有友好一点的解决方法？加载完成后获取webview内容高度然后设置LayoutParams?

**Comment by HzwSunshine** [comment]
试下1.2.2版本可以不，你的这个情况当时测试的时候考虑到了。webview的渲染是需要时间的，webview设置成wrap_content加载完成后闪屏是肯定的，我觉得有两种解决方式，第一：设置一个loading，渲染完成后隐藏，第二：webview设置为match_parent，调用setWebViewContentHeight方法手动设置webview的内容高度，这个内容高度可以让前端同学通过js传递给你
